import { readFileSync, writeFileSync, unlinkSync, renameSync, mkdirSync, readdirSync, existsSync } from 'fs';
import { join, dirname, extname, basename } from 'path';

const SRC = join(process.cwd(), 'src');
const ROOT = process.cwd();

// Map of old path -> new path (for files that need special handling)
const specialFiles = {
  'src/routeTree.gen.ts': 'src/routeTree.gen.ts', // Keep as .ts (generated by TanStack)
  'src/routes/README.md': 'src/routes/README.md', // Keep as-is
};

// Files to delete (lovable related)
const deleteFiles = [
  'src/lib/lovable-error-reporting.ts',
];

// Track all conversions for reporting
let converted = 0;
let deleted = 0;
let renamed = 0;

function stripTypescript(code) {
  let result = code;

  // Remove "use client" directive lines (they're Next.js-specific, not needed for TanStack Start/Vite)
  // Actually keep them as they might be used, but they're just string literals
  // Remove type imports
  result = result.replace(/import\s+type\s+\{[^}]*\}\s+from\s+['"][^'"]+['"]\s*;?/g, '');
  // Remove standalone type import
  result = result.replace(/import\s+type\s+\w+\s+from\s+['"][^'"]+['"]\s*;?/g, '');

  // Remove interface declarations
  result = result.replace(/export\s+interface\s+\w+[^{]*\{[^}]*(?:\{[^}]*\}[^}]*)*\}/g, '');
  result = result.replace(/interface\s+\w+[^{]*\{[^}]*(?:\{[^}]*\}[^}]*)*\}/g, '');

  // Remove type alias declarations (simple ones)
  result = result.replace(/export\s+type\s+\w+\s*=\s*[^;]+;/g, '');
  result = result.replace(/export\s+type\s*\{[^}]*\}\s*=\s*[^;]+;/g, '');
  result = result.replace(/type\s+\w+\s*=\s*[^;]+;/g, '');
  result = result.replace(/type\s+\w+\s*[<[][^)]*[)>]\s*=\s*[^;]+;/g, '');

  // Remove type annotations in function parameters and variables
  // Handle: param: Type -> param
  result = result.replace(/:\s*(?:string|number|boolean|void|any|unknown|never|object|Date|React\.|\w+(?:<[^>]*>)?)(?=[\s,)=;:.])/g, '');

  // Remove generic type parameters from functions: <T> -> <T> keep but remove bounds
  // Remove React.FC, React.FunctionComponent, React.ComponentProps, etc.
  result = result.replace(/React\.FC\s*[<[][^)>]*[)>]/g, '');
  result = result.replace(/React\.FunctionComponent\s*[<[][^)>]*[)>]/g, '');
  result = result.replace(/React\.ComponentProps<[^>]+>/g, '');
  result = result.replace(/React\.ComponentPropsWithoutRef<[^>]+>/g, '');
  result = result.replace(/React\.ComponentPropsWithRef<[^>]+>/g, '');
  result = result.replace(/React\.ElementRef<[^>]+>/g, '');
  result = result.replace(/React\.HTMLAttributes<[^>]+>/g, '');
  result = result.replace(/React\.HTMLElement[^,)]*/g, '');
  result = result.replace(/React\.MouseEventHandler<[^>]+>/g, '');
  result = result.replace(/React\.ChangeEventHandler<[^>]+>/g, '');
  result = result.replace(/React\.FormEventHandler<[^>]+>/g, '');
  result = result.replace(/React\.KeyboardEventHandler<[^>]+>/g, '');
  result = result.replace(/React\.PointerEventHandler<[^>]+>/g, '');
  result = result.replace(/VariantProps<[^>]+>/g, '');
  result = result.replace(/ComponentPropsWithoutRef<[^>]+>/g, '');
  result = result.replace(/ComponentProps<[^>]+>/g, '');
  result = result.replace(/ComponentPropsWithRef<[^>]+>/g, '');
  result = result.replace(/ElementRef<[^>]+>/g, '');
  result = result.replace(/HTMLAttributes<[^>]+>/g, '');

  // Remove ReactNode, React.ReactNode references in type positions
  result = result.replace(/ReactNode/g, 'any');
  result = result.replace(/React\.ReactNode/g, 'any');
  result = result.replace(/React\.JSX\.Element/g, 'any');
  result = result.replace(/JSX\.Element/g, 'any');
  result = result.replace(/JSXElement/g, 'any');

  // Remove type parameters from generic calls like useState<LibraryState>
  result = result.replace(/useState<[^>]+>/g, 'useState');
  result = result.replace(/useCallback<[^>]+>/g, 'useCallback');
  result = result.replace(/useMemo<[^>]+>/g, 'useMemo');
  result = result.replace(/useRef<[^>]+>/g, 'useRef');

  // Remove ReactNode type from type annotations
  result = result.replace(/:\s*ReactNode\b/g, '');

  // Remove type assertions (value as Type) -> value
  result = result.replace(/\sas\s+(?:React\.|HTML|Element|Node|JSX\w*|HTMLElement|ComponentType|FC)\b/g, '');
  result = result.replace(/\sas\s+(?:Record|Partial|Pick|Omit|Exclude|Extract|NonNullable)\s*<[^>]+>/g, '');

  // Remove `?:` from type annotations in type aliases but keep optional params in functions
  // Actually this is tricky, let me handle specific patterns

  // Remove `satisfies` keyword and its type (used in library.ts)
  result = result.replace(/\s*satisfies\s+\w+/g, '');

  // Remove type from type parameters in function return types
  result = result.replace(/:\s*(Promise<[^>]+>)\s*=>/g, '=>');

  // Clean up any remaining `type` keyword in type positions
  // Remove `type Song = { ... }` patterns
  result = result.replace(/export\s+type\s+\w+\s*=\s*[{][^}]*[}]\s*;/g, '');

  // Remove `: Type` from type alias definitions that have already been removed
  // Clean up leftover commas and empty lines from removed type annotations

  // Remove `as const` assertions
  result = result.replace(/\s+as\s+const/g, '');

  // Remove `?:` in type positions (keep in interface/type which we already removed)
  // For function parameters, keep optional marking `?` but remove type
  // This is handled by the regex above

  // Remove `| null` and `| undefined` type annotations from parameters
  // But keep in actual code logic

  // Remove `|` union types from function parameter type annotations
  // e.g., files: FileList | File[] -> files:
  // This is complex, handled by the generic type removal above

  // Remove trailing commas in empty type positions
  // Clean up multiple spaces
  result = result.replace(/  +/g, '  ');

  return result;
}

function processFile(inputPath, outputPath, ext) {
  const code = readFileSync(inputPath, 'utf-8');

  // Skip auto-generated route tree
  if (inputPath.includes('routeTree.gen')) {
    return;
  }

  let processed = stripTypescript(code);

  // If it's a .tsx file, change to .jsx
  // If it's a .ts file, change to .js
  writeFileSync(outputPath, processed, 'utf-8');
  converted++;
}

// First, handle deletions
for (const file of deleteFiles) {
  const fullPath = join(ROOT, file);
  if (existsSync(fullPath)) {
    unlinkSync(fullPath);
    deleted++;
    console.log(`Deleted: ${file}`);
  }
}

// Also remove the reportLovableError call from __root.tsx before converting
const rootPath = join(ROOT, 'src/routes/__root.tsx');
if (existsSync(rootPath)) {
  let content = readFileSync(rootPath, 'utf-8');
  content = content.replace(/import\s+\{ reportLovableError \}\s+from\s+["']\.\.\/lib\/lovable-error-reporting["']\s*;?\n?/g, '');
  content = content.replace(/reportLovableError\(error,\s*\{[^}]*\}\)\s*;?\n?/g, '');
  // Update the ErrorComponent to not use reportLovableError
  content = content.replace(
    /useEffect\(\(\) => \{\s*reportLovableError\(error,\s*\{[^}]*\}\)\s*;\s*\}, \[error\]\);/s,
    ''
  );
  // Remove any leftover useEffect import if it was only used for reportLovableError
  // Actually keep useEffect as it's used elsewhere
  writeFileSync(rootPath, content, 'utf-8');
}

// Now scan all source files
function scanDir(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules') continue;
      scanDir(fullPath);
    } else if (entry.isFile()) {
      const ext = extname(entry.name);
      const name = entry.name.replace(ext, '');

      // Skip non-source files
      if (!['.tsx', '.ts', '.jsx', '.js'].includes(ext)) continue;

      // Skip generated route tree
      if (entry.name === 'routeTree.gen.ts') continue;

      // Skip if already deleted
      if (entry.name === 'lovable-error-reporting.ts') continue;

      let newExt;
      if (ext === '.tsx') newExt = '.jsx';
      else if (ext === '.ts') newExt = '.js';
      else { newExt = ext; }

      const newName = name + newExt;
      const newPath = join(dirname(fullPath), newName);

      if (fullPath !== newPath) {
        // Process the file
        processFile(fullPath, newPath, newExt);
        unlinkSync(fullPath);
        renamed++;
        console.log(`Converted: ${fullPath} -> ${newPath}`);
      } else {
        // Same extension (already .js/.jsx)
        processFile(fullPath, newPath, newExt);
      }
    }
  }
}

console.log('Starting conversion...\n');
scanDir(SRC);

console.log(`\nConversion complete!`);
console.log(`Converted: ${converted} files`);
console.log(`Deleted: ${deleted} files`);
console.log(`Renamed: ${renamed} files`);
