/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it is checked or modified.

import { Route as rootRouteImport } from './routes/__root.jsx'
import { Route as IndexRouteImport } from './routes/index.jsx'
import { Route as AlbumsRouteImport } from './routes/albums.jsx'
import { Route as ArtistsRouteImport } from './routes/artists.jsx'
import { Route as FavoritesRouteImport } from './routes/favorites.jsx'
import { Route as RecentRouteImport } from './routes/recent.jsx'
import { Route as SearchRouteImport } from './routes/search.jsx'
import { Route as SongsRouteImport } from './routes/songs.jsx'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index.jsx'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId.jsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
})
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
})
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
})
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
})
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
})
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
})
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
})
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  ArtistsRoute: ArtistsRoute,
  FavoritesRoute: FavoritesRoute,
  RecentRoute: RecentRoute,
  SearchRoute: SearchRoute,
  SongsRoute: SongsRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()

import { getRouter } from './router.jsx'
import { startInstance } from './start.js'
